"use client";
import { useEffect, useRef, useState, useCallback } from "react";
import { createPortal } from "react-dom";

// ── Tour step definitions ─────────────────────────────────────────────────────
export const TOUR_STEPS = [
  {
    target: "[data-tour='kpis']",
    title: "Live KPI Dashboard",
    body: "Four real-time counters pulled from the backend every second via WebSocket. Active Disruptions, Idle Fleet, Critical Shipments, and Cold-Chain Alerts all update automatically as the pipeline runs.",
    placement: "bottom" as const,
  },
  {
    target: "[data-tour='scenarios']",
    title: "Simulate a Disruption",
    body: "Click any card to trigger a real pipeline run: the backend fires the Impact Engine → Risk Engine → Route Optimizer → Fleet Matcher in sequence. Watch the card expand with live step progress as each engine completes.",
    placement: "bottom" as const,
  },
  {
    target: "[data-tour='map']",
    title: "Live Fleet & Disruption Map",
    body: "All shipments, idle fleet trucks, and the active disruption zone rendered in real time. When you click 'See on Map' on a recommendation, the map shows the BLOCKED route (red dashed) vs the AI REROUTE (green animated) side-by-side, with a cyan line showing which truck is being dispatched.",
    placement: "right" as const,
  },
  {
    target: "[data-tour='action-center']",
    title: "AI Action Center",
    body: "Every recommendation is generated by watsonx.ai (Llama 4 Maverick). Each card shows the PROBLEM (what's blocked) and the AI FIX (alternate route with cost/time delta). Click 'See on Map' to visualise it, then Approve or Reject — every decision is logged to the Audit Trail.",
    placement: "left" as const,
  },
  {
    target: "[data-tour='incidents']",
    title: "Active Incidents",
    body: "Cold-chain excursions and disruption alerts arrive here in real time. Each excursion is classified Minor / Major / Critical by watsonx.ai against GDP pharmaceutical guidelines — the same standard used in FDA/EMA audits.",
    placement: "top" as const,
  },
  {
    target: "[data-tour='sensor-feed']",
    title: "Live Sensor Feed",
    body: "Simulated IoT temperature readings arrive every 5 seconds per shipment. Red = above 8°C threshold (excursion). The coldChainEngine opens an incident automatically when readings breach the configured rule profile.",
    placement: "top" as const,
  },
  {
    target: "[data-tour='audit']",
    title: "Audit Trail",
    body: "Every Approve and Reject action is written as an immutable AuditEvent with a timestamp and actor ID. This is the compliance record — required for FDA/EMA traceability and GDP documentation.",
    placement: "top" as const,
  },
  {
    target: "[data-tour='chat']",
    title: "AI Operations Copilot",
    body: "Ask anything in plain English: 'Which shipments are most at risk?', 'Why is this reroute recommended?', 'What's the status of SHIP-101?' — watsonx.ai answers with full live context: current shipments, disruptions, idle fleet, and open excursions.",
    placement: "top" as const,
  },
];

// ── Geometry helper ───────────────────────────────────────────────────────────
function getRect(selector: string): DOMRect | null {
  const el = document.querySelector(selector);
  return el ? el.getBoundingClientRect() : null;
}

const PAD = 10; // px padding around highlighted element
const TIP_W = 340; // tooltip width px

// ── Main component ────────────────────────────────────────────────────────────
export default function TourOverlay({ onDone }: { onDone: () => void }) {
  const [step, setStep] = useState(0);
  const [rect, setRect] = useState<DOMRect | null>(null);
  const [mounted, setMounted] = useState(false);
  const rafRef = useRef<number | null>(null);

  const current = TOUR_STEPS[step];
  const total   = TOUR_STEPS.length;

  // Recalculate target rect (handles scroll / resize)
  const recalc = useCallback(() => {
    const r = getRect(current.target);
    setRect(r);
  }, [current.target]);

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    recalc();
    // Poll so rect stays updated while user scrolls during the tour
    let live = true;
    const poll = () => {
      if (!live) return;
      recalc();
      rafRef.current = requestAnimationFrame(poll);
    };
    rafRef.current = requestAnimationFrame(poll);
    return () => {
      live = false;
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
    };
  }, [recalc]);

  const goNext = () => {
    if (step < total - 1) {
      setStep(s => s + 1);
      // Scroll target into view
      const el = document.querySelector(TOUR_STEPS[step + 1].target);
      el?.scrollIntoView({ behavior: "smooth", block: "center" });
    } else {
      onDone();
    }
  };
  const goPrev = () => {
    if (step > 0) {
      setStep(s => s - 1);
      const el = document.querySelector(TOUR_STEPS[step - 1].target);
      el?.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  };

  if (!mounted) return null;

  // ── Tooltip position calculation ─────────────────────────────────────────
  let tipTop = 0, tipLeft = 0;
  const vw = typeof window !== "undefined" ? window.innerWidth : 1200;
  const vh = typeof window !== "undefined" ? window.innerHeight : 800;

  if (rect) {
    const p = current.placement;
    if (p === "bottom") {
      tipTop  = rect.bottom + PAD + 8;
      tipLeft = rect.left + rect.width / 2 - TIP_W / 2;
    } else if (p === "top") {
      tipTop  = rect.top - PAD - 8 - 160; // approx tooltip height
      tipLeft = rect.left + rect.width / 2 - TIP_W / 2;
    } else if (p === "right") {
      tipTop  = rect.top + rect.height / 2 - 80;
      tipLeft = rect.right + PAD + 8;
    } else { // left
      tipTop  = rect.top + rect.height / 2 - 80;
      tipLeft = rect.left - TIP_W - PAD - 8;
    }
    // Clamp to viewport
    tipLeft = Math.max(12, Math.min(tipLeft, vw - TIP_W - 12));
    tipTop  = Math.max(12, Math.min(tipTop, vh - 200));
  }

  // ── Cutout SVG clip path ──────────────────────────────────────────────────
  // We render a full-screen dark overlay with a transparent hole cut around the target
  const cutout = rect
    ? `M0,0 H${vw} V${vh} H0 Z M${rect.left - PAD},${rect.top - PAD} H${rect.right + PAD} V${rect.bottom + PAD} H${rect.left - PAD} Z`
    : `M0,0 H${vw} V${vh} H0 Z`;

  return createPortal(
    <div className="fixed inset-0 z-[99990] pointer-events-none" aria-modal role="dialog" aria-label="Product tour">

      {/* Overlay with cutout */}
      <svg
        className="absolute inset-0 w-full h-full pointer-events-auto"
        style={{ cursor: "default" }}
        onClick={onDone}
        aria-hidden
      >
        <path d={cutout} fill="rgba(6,11,20,0.82)" fillRule="evenodd" />
        {/* Highlight border */}
        {rect && (
          <rect
            x={rect.left - PAD} y={rect.top - PAD}
            width={rect.width + PAD * 2} height={rect.height + PAD * 2}
            rx={8} fill="none"
            stroke="#3b82f6" strokeWidth={1.5} strokeOpacity={0.6}
            strokeDasharray="6 4"
          />
        )}
      </svg>

      {/* Tooltip card */}
      <div
        className="absolute pointer-events-auto"
        style={{ top: tipTop, left: tipLeft, width: TIP_W }}
      >
        <div className="bg-[#0b1424] border border-slate-700/70 rounded-2xl shadow-2xl shadow-black/70 overflow-hidden">

          {/* Header */}
          <div className="flex items-center justify-between px-4 pt-3.5 pb-2 border-b border-slate-800/60">
            <div className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-blue-500 animate-pulse" />
              <span className="text-[9px] font-bold uppercase tracking-widest text-blue-400">
                Step {step + 1} of {total}
              </span>
            </div>
            <button
              onClick={onDone}
              className="text-slate-600 hover:text-slate-300 text-[16px] leading-none transition-colors"
              aria-label="Close tour"
            >×</button>
          </div>

          {/* Body */}
          <div className="px-4 py-3">
            <div className="text-[13px] font-bold text-white mb-1.5">{current.title}</div>
            <div className="text-[11px] text-slate-400 leading-relaxed">{current.body}</div>
          </div>

          {/* Progress dots */}
          <div className="flex items-center justify-center gap-1 pb-3">
            {TOUR_STEPS.map((_, i) => (
              <span
                key={i}
                className={`rounded-full transition-all duration-300 ${
                  i === step
                    ? "w-4 h-1.5 bg-blue-500"
                    : i < step
                    ? "w-1.5 h-1.5 bg-blue-500/40"
                    : "w-1.5 h-1.5 bg-slate-700"
                }`}
              />
            ))}
          </div>

          {/* Navigation */}
          <div className="flex gap-2 px-4 pb-4">
            {step > 0 && (
              <button
                onClick={goPrev}
                className="px-3 py-1.5 text-[10px] font-semibold text-slate-400 hover:text-white border border-slate-700 hover:border-slate-500 rounded-lg transition-colors"
              >← Back</button>
            )}
            <button
              onClick={goNext}
              className="flex-1 py-1.5 text-[11px] font-bold text-white bg-blue-600 hover:bg-blue-500 rounded-lg transition-colors"
            >
              {step < total - 1 ? "Next →" : "Finish Tour ✓"}
            </button>
          </div>
        </div>
      </div>
    </div>,
    document.body
  );
}
